# Generated by Django 4.0.3 on 2022-05-19 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='Tell us about yourself!', max_length=500)),
                ('gender', models.TextField(max_length=20)),
                ('ethnicity', models.TextField(default='WHITE', max_length=20)),
                ('relationship_type', models.TextField(default='DONT KNOW YET', max_length=100)),
                ('kids', models.TextField(default='NOT SURE YET', max_length=100)),
                ('height', models.IntegerField()),
                ('looking_for', models.TextField(default='BOTH', max_length=6)),
                ('location', models.TextField(default='', max_length=100)),
                ('birth_date', models.DateField(blank=True, default='1990-01-01', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('content', models.CharField(max_length=200, verbose_name='comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
