# Generated by Django 4.0.3 on 2022-05-16 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='Tell us about yourself!', max_length=500)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6)),
                ('ethnicity', models.CharField(choices=[('WHITE', 'White'), ('ASIAN: INDIAN', 'Asian: Indian'), ('ASIAN: PAKISTANI', 'Asian: Pakistani'), ('ASIAN: BANGLADESHI', 'Asian: Bangladeshi'), ('ASIAN: CHINESE', 'Asian: Chinese'), ('BLACK', 'Black'), ('MIXED', 'Mixed'), ('OTHER ETHNICITY', 'Other Ethnicity')], default='WHITE', max_length=100)),
                ('relationship_type', models.CharField(choices=[('RELATIONSHIP', 'relationship'), ('SOMETHING CASUAL', 'something casual'), ('DONT KNOW YET', 'dont know yet'), ('MARRIAGE', 'marriage')], default='NEVER MARRIED', max_length=100)),
                ('kids', models.CharField(choices=[('WANT SOMEDAY', 'WANT SOMEDAY'), ('DO NOT WANT', 'do not want'), ('HAVE AND WANT MORE', 'have and want more'), ('HAVE AND DO NOT WANT MORE', 'have and do not want more'), ('NOT SURE YET', 'NOT SURE YET')], default='NOT SURE YET', max_length=100)),
                ('height', models.DecimalField(decimal_places=2, default=180.34, max_digits=10)),
                ('looking_for', models.CharField(choices=[('MALE', 'Men'), ('FEMALE', 'Women'), ('BOTH', 'Both')], default='BOTH', max_length=6)),
                ('location', models.CharField(default='', max_length=100)),
                ('citylat', models.DecimalField(decimal_places=6, default='-2.0180319', max_digits=9)),
                ('citylong', models.DecimalField(decimal_places=6, default='52.5525525', max_digits=9)),
                ('birth_date', models.DateField(blank=True, default='1990-01-01', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
    ]
