# Generated by Django 4.0.3 on 2022-05-18 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='user',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='citylat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='citylong',
        ),
        migrations.AlterField(
            model_name='profile',
            name='ethnicity',
            field=models.TextField(default='WHITE', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kids',
            field=models.TextField(default='NOT SURE YET', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.TextField(default='BOTH', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_type',
            field=models.TextField(default='DONT KNOW YET', max_length=100),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('content', models.CharField(max_length=200, verbose_name='comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
