# Generated by Django 4.0.3 on 2022-05-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='citylat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='citylong',
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_type',
            field=models.CharField(choices=[('RELATIONSHIP', 'relationship'), ('SOMETHING CASUAL', 'something casual'), ('DONT KNOW YET', 'dont know yet'), ('MARRIAGE', 'marriage')], default='DONT KNOW YET', max_length=100),
        ),
    ]
