# Generated by Django 4.0.3 on 2022-05-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_profile_citylat_remove_profile_citylong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(choices=[('WHITE', 'White'), ('ASIAN: INDIAN', 'Asian: Indian'), ('ASIAN: PAKISTANI', 'Asian: Pakistani'), ('ASIAN: BANGLADESHI', 'Asian: Bangladeshi'), ('ASIAN: CHINESE', 'Asian: Chinese'), ('FILIPINO', 'FILIPINO'), ('BLACK', 'Black'), ('MIXED', 'Mixed'), ('OTHER ETHNICITY', 'Other Ethnicity')], default='WHITE', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.TextField(max_length=20),
        ),
    ]
