# Generated by Django 4.0.3 on 2022-05-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_user_photo_profile_alter_profile_ethnicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(),
        ),
    ]
